# Generated by Django 4.0.6 on 2022-07-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=64)),
                ('nim', models.IntegerField()),
                ('jurusan', models.CharField(max_length=64)),
                ('umur', models.IntegerField()),
            ],
        ),
    ]
